app:
  number_of_threads: 1
  max_tweets: 100
  max_time_in_milliseconds: 30000
twitter:
  consumer_key: RLSrphihyR4G2UxvA0XBkLAdl
  consumer_secret: FTz2KcP1y3pcLw0XXMX5Jy3GTobqUweITIFy4QefullmpPnKm4
  search: bieber

